from .abc import Hooker as Hooker
from .sessions import HTTPSession as HTTPSession
from typing import Any, Optional

class InvalidHost(TypeError):
    def __init__(self, host: Optional[str]) -> None: ...

class HookerError(Exception):
    hooker: Hooker = ...
    client: HTTPSession = ...
    def __init__(self, message: Optional[str]=..., *, hooker: Hooker, client: HTTPSession) -> None: ...

class HookerAlreadyConnected(HookerError): ...
class HookerClosed(HookerError): ...
class HandshakeError(HookerError): ...
