from .abc import Hooker as Hooker
from typing import Optional

class InvalidHost(TypeError):
    def __init__(self, host: Optional[str]) -> None: ...

class HookerError(Exception):
    hooker: Hooker = ...
    def __init__(self, message: Optional[str]=..., *, hooker: Hooker) -> None: ...

class HookerAlreadyConnected(HookerError): ...
class HookerClosed(HookerError): ...
class HandshakeError(HookerError): ...
