from typing import Any, Dict, Optional

class HTTPRequest:
    method: str = ...
    path: str = ...
    host: str = ...
    headers: Dict[str, Any] = ...
    body: Any = ...
    def __init__(self, method: str, path: str, host: str, headers: Dict[str, Any], body: Optional[str]) -> None: ...
    def encode(self): ...
