from .errors import InvalidHost as InvalidHost
from typing import Any, Coroutine, Generator, Generic, TypeVar

T = TypeVar('T')

class AsyncContextManager(Generic[T]):
    coro: Coroutine[Any, Any, T] = ...
    def __init__(self, coroutine: Coroutine[Any, Any, T]) -> None: ...
    def __await__(self) -> Generator[None, None, T]: ...
    async def __aenter__(self) -> T: ...
    async def __aexit__(self, *args: Any) -> Any: ...

