import asyncio
from typing import Any

def new_event_loop() -> asyncio.AbstractEventLoop: ...
def set_event_loop(loop: Any) -> None: ...
def get_running_loop() -> asyncio.AbstractEventLoop: ...
def get_event_loop() -> asyncio.AbstractEventLoop: ...
def get_event_loop_policy() -> asyncio.AbstractEventLoopPolicy: ...
