from .request import Request as Request
from typing import Any, Optional

class Cookie:
    name: str = ...
    value: Any = ...
    http_only: bool = ...
    secure: bool = ...
    def __init__(self, name: str, value: str, domain: Optional[str], http_only: bool, secure: bool) -> None: ...
    def set_domain(self, domain: str) -> None: ...

class CookieJar:
    def __init__(self) -> None: ...
    @classmethod
    def from_request(cls: Any, request: Request) -> CookieJar: ...
    def add_cookie(self, name: str, value: str, *, domain: Optional[str]=..., http_only: bool=..., is_secure: bool=...) -> Any: ...
    def get_cookie(self, name: str) -> Optional[Cookie]: ...
    def encode(self): ...
    def __iter__(self) -> Any: ...
    def __bool__(self): ...
    def __len__(self): ...
