class railwayException(Exception): ...
class ApplicationError(Exception): ...
class ConnectionError(railwayException): ...
class BadConversion(ApplicationError): ...
class InvalidSetting(ApplicationError): ...
class RegistrationError(ApplicationError): ...
