from .objects import Listener, Middleware, Route
from typing import Any, Dict, List, Tuple, Type

class InjectableMeta(type):
    __routes__: List[Route] = ...
    __listeners__: List[Listener] = ...
    __middlewares__: List[Middleware] = ...
    def __new__(cls: Any, name: str, bases: Tuple[Type[Any]], attrs: Dict[str, Any], **kwargs: Any) -> Any: ...

class Injectable:
    __routes__: List[Route]
    __listeners__: List[Listener]
    __middlewares__: List[Middleware]
