import asyncio

class Semaphore:
    def __init__(self, value: int, *, loop: asyncio.AbstractEventLoop=...) -> None: ...
    @property
    def value(self) -> int: ...
    @property
    def loop(self) -> asyncio.AbstractEventLoop: ...
    def is_locked(self) -> bool: ...
    def wakeup(self) -> None: ...
    async def wait(self) -> None: ...
    async def acquire(self, *, wait: bool=...) -> bool: ...
    def release(self) -> None: ...
    async def __aenter__(self) -> None: ...
    async def __aexit__(self, *args) -> None: ...

class Lock:
    def __init__(self, *, loop: asyncio.AbstractEventLoop=...) -> None: ...
    @property
    def loop(self) -> asyncio.AbstractEventLoop: ...
    def is_locked(self) -> bool: ...
    async def wait(self) -> None: ...
    async def acquire(self, *, wait: bool=...) -> bool: ...
    def release(self) -> None: ...
    async def __aenter__(self) -> None: ...
    async def __aexit__(self, *args) -> None: ...