from .request import Request as Request
from typing import Any, Dict, Optional

class CookieSession(Dict[str, Any]):
    cache: Dict[str, CookieSession] = ...
    id: str = ...
    @classmethod
    def create(cls: Any, session_id: str) -> CookieSession: ...
    @classmethod
    def from_request(cls: Any, request: Request) -> CookieSession: ...
    def __init__(self, session_id: Optional[str]) -> None: ...
