import asyncio
from typing import Any, List, Optional, Union


class StreamWriter:
    def __init__(self, transport: asyncio.Transport) -> None: ...
    @property
    def transport(self) -> asyncio.Transport: ...
    async def write(self, data: Union[bytearray, bytes], *, timeout: float=...) -> None: ...
    async def writelines(self, data: List[Union[bytearray, bytes]], *, timeout: float=...) -> None: ...
    def get_extra_info(self, name: str, default: Any=...) -> Any: ...
    def close(self) -> None: ...

class StreamReader:
    buffer: bytearray = ...
    loop: asyncio.AbstractEventLoop = ...
    def __init__(self, loop: Optional[asyncio.AbstractEventLoop]=...) -> None: ...
    def feed_data(self, data: Union[bytearray, bytes]) -> None: ...
    def feed_eof(self) -> None: ...
    async def read(self, nbytes: Optional[int]=..., *, timeout: Optional[float]=...) -> bytes: ...

class StreamTransport:
    def __init__(self, transport: asyncio.Transport) -> None: ...
    def get_extra_info(self, name: str, default: Any=...) -> Any: ...
    def get_protocol(self) -> asyncio.Protocol: ...
    def close(self) -> None: ...
    def abort(self) -> None: ...
    def is_closing(self) -> bool: ...
    def is_reading(self) -> bool: ...
    def feed_data(self, data: Union[bytes, bytearray]) -> None: ...
    def feed_eof(self) -> None: ...
    async def receive(self, nbytes: int=..., *, timeout: float=...) -> bytes: ...
    async def write(self, data: Union[bytearray, bytes], *, timeout: float=...) -> None: ...
    async def writelines(self, data: List[Union[bytearray, bytes]], *, timeout: float=...) -> None: ...
    