import ctypes
from typing import Any

class Overlapped: 
    address: int
    overlapped: Any
    event: Any
    handle: Any
    pending: bool
    def WSARecv(self, handle: int, nbytes: int, flags: int): ...
    def WSASend(self, handle: int, bufobj: bytes, flags: int): ...
    def ConnectNamedPipe(self, handle: int): ...
    def cancel(self): ...
    def getresult(self, wait: bool=...): ...